apiVersion: apps/v1
kind: Deployment
metadata:
  name: aetherium-deployment
  labels:
    app: aetherium
    version: v1.0.0
    component: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: aetherium
  template:
    metadata:
      labels:
        app: aetherium
        version: v1.0.0
        component: frontend
    spec:
      # Add host aliases to inject custom DNS entries into /etc/hosts
      hostAliases:
      - ip: "192.168.1.100"  # Replace with your actual IP
        hostnames:
        - "api-preprod.e-tayssir.alsalamalgeria.local"
      - ip: "192.168.1.101"  # Add more entries as needed
        hostnames:
        - "api-staging.e-tayssir.alsalamalgeria.local"
        - "internal-service.company.local"
      
      containers:
      - name: aetherium
        image: ramybouchareb/aetherium
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3000"
        - name: HOSTNAME
          value: "0.0.0.0"
        # Custom DNS mappings for domains not available in pod
        - name: DNS_MAPPINGS
          value: "api-preprod.e-tayssir.alsalamalgeria.local=192.168.1.100,api-staging.e-tayssir.alsalamalgeria.local=192.168.1.101"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: aetherium-service
  labels:
    app: aetherium
    service: aetherium
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: aetherium
